version: "2"

services:
  mongo:
    image: mongo:3.2
    networks:
      - back-tier
    volumes:
      - ./data/mongo:/data/db

  redis:
    image: redis:3.2.0
    networks:
      - back-tier
    volumes:
      - ./data/redis:/data

  server:
    build:
      context: ../source/server
      dockerfile: Dockerfile.pro
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo/tests
      - REDIS_URL=redis://redis:6379
    ports:
      - 4000:4000
    networks:
      - back-tier
    volumes:
      - ../source/server/logs:/usr/src/app/logs
    depends_on:
      - mongo
      - redis

networks:
  back-tier:
  # front-tier:
# volumes:
  # db-data:
