version: "2"

services:
  mongo:
    image: mongo:3.2
    networks:
      - back-tier
    volumes:
      - ./data/mongo:/data/db

  redis:
    image: redis:3.2.0
    networks:
      - back-tier
    volumes:
      - ./data/redis:/data

  server:
    build:
      context: ../source/server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ../source/server/bin:/usr/src/app/bin
      - ../source/server/src:/usr/src/app/src
      - ../source/server/logs:/usr/src/app/logs
      - ../source/server/config:/usr/src/app/config
    ports:
      - 4000:4000
    networks:
      - back-tier

  client:
    image: ubuntu:14.04
    command: /bin/echo 'Hello world'

networks:
  back-tier:
  # front-tier:
# volumes:
  # db-data:
