version: "2"

services:

  server:
    environment:
      - NODE_ENV=development
    volumes:
      - ../source/server/bin:/usr/src/app/bin
      - ../source/server/src:/usr/src/app/src
      - ../source/server/logs:/usr/src/app/logs
      - ../source/server/config:/usr/src/app/config
      - ../source/server/private:/usr/src/app/private
    command: "./bin/dumb-db.sh"
