version: "2"

services:
  mongo:
    image: mongo:3.2
    networks:
      - back-tier

  server:
    build:
      context: ../source/server
      dockerfile: Dockerfile
    volumes:
      - ../source/server/src:/usr/src/app/src
    ports:
      - 4000:4000
    networks:
      - back-tier

  client:
    image: ubuntu:14.04
    command: /bin/echo 'Hello world'

networks:
  back-tier:
  front-tier:
# volumes:
  # db-data:
