version: "2"

services:
  mongo:
    image: mongo:3.2
    networks:
      - back-tier
    volumes:
      - ./data/mongo:/data/db

  redis:
    image: redis:3.2.0
    networks:
      - back-tier
    volumes:
      - ./data/redis:/data

  server:
    build:
      context: ../source/server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ../source/server/bin:/usr/src/app/bin
      - ../source/server/src:/usr/src/app/src
      - ../source/server/logs:/usr/src/app/logs
      - ../source/server/config:/usr/src/app/config
      - ../source/server/private:/usr/src/app/private
    ports:
      - 4000:4000
    networks:
      - back-tier
    depends_on:
      - mongo
      - redis

  client:
    build:
      context: ../source/client
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ../source/client/app:/usr/src/app/app
    ports:
      - 3000:3000
    networks:
      - front-tier
    command: bash -c "npm run build:dll && npm run start"

networks:
  back-tier:
  front-tier:
# volumes:
  # db-data:
