version: "2"

services:
  mongo:
    volumes:
      - ./data/mongo:/data/db

  redis:
    volumes:
      - ./data/redis:/data

  server:
    build:
      context: ../source/server
      dockerfile: Dockerfile.pro
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo/tests
      - REDIS_URL=redis://redis:6379
    volumes:
      - ../source/server/logs:/usr/src/app/logs
    depends_on:
      - mongo
      - redis

  client:
    build:
      context: ../source/client
      dockerfile: Dockerfile.pro
    environment:
      - NODE_ENV=production
    ports:
      - 80:80
